import puppeteer from 'puppeteer-core';
const b=await puppeteer.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:'new',args:['--no-sandbox']});
const p=await b.newPage();
await p.setViewport({width:390,height:844,deviceScaleFactor:2,isMobile:true,hasTouch:true});
await p.goto('https://bw5-app.vercel.app/merch/tshirt',{waitUntil:'networkidle0',timeout:120000});
await new Promise(r=>setTimeout(r,4000));
await p.evaluate(()=>localStorage.clear());
await p.reload({waitUntil:'networkidle0'}); await new Promise(r=>setTimeout(r,3500));
await p.evaluate(()=>{
  const set=(el,v)=>{Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set.call(el,v);el.dispatchEvent(new Event('input',{bubbles:true}));};
  const inputs=[...document.querySelectorAll('input')];
  set(inputs.find(i=>i.placeholder?.includes('ブーム')),'メール テスト');
  set(inputs.find(i=>i.placeholder?.includes('example.com')),'boom.sendai@gmail.com');
  [...document.querySelectorAll('button')].find(b=>b.textContent.trim()==='M').click();
});
await p.evaluate(()=>{[...document.querySelectorAll('button')].find(b=>b.textContent.trim()==='注文する').click()});
await new Promise(r=>setTimeout(r,4000));
const t=await p.evaluate(()=>document.body.innerText.slice(0,300));
console.log(t.includes('ご注文を承りました') ? '✅ 注文成立(現金・boom.sendai宛)' : '❌ '+t.slice(0,120));
console.log(t.includes('確認メールをお送りしました') ? '✅ 完了画面にメール案内' : '❌ 案内なし');
await b.close();
